repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.11
    hooks:
      - id: ruff-format
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
        args: ["--assume-in-merge"]
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key
  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: uv run ty check .
        language: system
        pass_filenames: false
        types: [python]
